export const TAB_BAR_HEIGHT = 56;
export const FLOATING_BUTTON_SIZE = 56;
export const FLOATING_BUTTON_MARGIN = 16;
export const FLOATING_BUTTON_BOTTOM = TAB_BAR_HEIGHT + FLOATING_BUTTON_MARGIN;
export const FLOATING_BUTTON_CLEARANCE = FLOATING_BUTTON_SIZE + FLOATING_BUTTON_MARGIN * 2;
