import _ from 'lodash';
import {
  REACT_NATIVE_DRIVE_API_URL,
  REACT_NATIVE_PHOTOS_API_URL,
  REACT_NATIVE_CRYPTO_SECRET,
  REACT_NATIVE_CRYPTO_SECRET2,
  REACT_NATIVE_MAGIC_IV,
  REACT_NATIVE_MAGIC_SALT,
  REACT_NATIVE_RECAPTCHA_V3,
} from '@env';

export async function loadEnvVars(): Promise<boolean> {
  const REQUIRED_ENVS = [
    REACT_NATIVE_DRIVE_API_URL,
    REACT_NATIVE_PHOTOS_API_URL,
    REACT_NATIVE_CRYPTO_SECRET,
    REACT_NATIVE_CRYPTO_SECRET2,
    REACT_NATIVE_MAGIC_IV,
    REACT_NATIVE_MAGIC_SALT,
    REACT_NATIVE_RECAPTCHA_V3,
  ];

  const VALID_ENVS = _.filter(REQUIRED_ENVS, _.size);

  if (VALID_ENVS.length !== REQUIRED_ENVS.length) {
    throw Error('Check your envs');
  }
  return true;
}
