export const fileActionTypes = {
  GET_FILES_REQUEST: 'GET_FILES_REQUEST',
  GET_FILES_SUCCESS: 'GET_FILES_SUCCESS',
  GET_FILES_FAILURE: 'GET_FILES_FAILURE',

  SELECT_FILE: 'SELECT_FILE',
  DESELECT_FILE: 'DESELECT_FILE',
  DESELECT_ALL: 'DESELECT_ALL',

  SET_SORT_TYPE: 'SET_SORT_TYPE',

  SET_SEARCH_STRING: 'SET_SEARCH_STRING',

  DOWNLOAD_SELECTED_FILE_START: 'DOWNLOAD_SELECTED_FILE_START',
  DOWNLOAD_SELECTED_FILE_STOP: 'DOWNLOAD_SELECTED_FILE_STOP',

  ADD_FILE_REQUEST: 'ADD_FILE_REQUEST',
  ADD_FILE_SUCCESS: 'ADD_FILE_SUCCESS',
  ADD_FILE_FAILURE: 'ADD_FILE_FAILURE',
  ADD_FILE_UPLOAD_PROGRESS: 'ADD_FILE_UPLOAD_PROGRESS',
  SET_FILE_UPLOAD_URI: 'SET_FILE_UPLOAD_URI',

  UPDATE_FILE_REQUEST: 'UPDATE_FILE_REQUEST',
  UPDATE_FILE_SUCCESS: 'UPDATE_FILE_SUCCESS',
  UPDATE_FILE_FAILURE: 'UPDATE_FILE_FAILURE',

  DELETE_FILE_REQUEST: 'DELETE_FILE_REQUEST',
  DELETE_FILE_SUCCESS: 'DELETE_FILE_SUCCESS',
  DELETE_FILE_FAILURE: 'DELETE_FILE_FAILURE',

  CREATE_FOLDER_REQUEST: 'CREATE_FOLDER_REQUEST',
  CREATE_FOLDER_SUCCESS: 'CREATE_FOLDER_SUCCESS',
  CREATE_FOLDER_FAILURE: 'CREATE_FOLDER_FAILURE',

  UPDATE_FOLDER_METADATA_REQUEST: 'UPDATE_FOLDER_METADATA_REQUEST',
  UPDATE_FOLDER_METADATA_SUCCESS: 'UPDATE_FOLDER_METADATA_SUCCESS',
  UPDATE_FOLDER_METADATA_FAILURE: 'UPDATE_FOLDER_METADATA_FAILURE',

  MOVE_FILES_REQUEST: 'MOVE_FILES_REQUEST',
  MOVE_FILES_SUCCESS: 'MOVE_FILES_SUCCESS',
  MOVE_FILES_FAILURE: 'MOVE_FILES_FAILURE',

  DOWNLOAD_FILE_START: 'DOWNLOAD_FILE_START',
  DOWNLOAD_FILE_END: 'DOWNLOAD_FILE_END'
};
