export const layoutActionTypes = {
  OPEN_SEARCH_FORM: 'OPEN_SEARCH_FORM',
  CLOSE_SEARCH_FORM: 'CLOSE_SEARCH_FORM',

  OPEN_SETTINGS_MODAL: 'OPEN_SETTINGS_MODAL',
  CLOSE_SETTINGS_MODAL: 'CLOSE_SETTINGS_MODAL',

  OPEN_ITEM_MODAL: 'OPEN_ITEM_MODAL',
  CLOSE_ITEM_MODAL: 'CLOSE_ITEM_MODAL',

  OPEN_RUNOUTSTORAGE_MODAL: 'OPEN_RUNOUTSTORAGE_MODAL',
  CLOSE_RUNOUTSTORAGE_MODAL: 'CLOSE_RUNOUTSTORAGE_MODAL',

  OPEN_SORT_MODAL: 'OPEN_SORT_MODAL',
  CLOSE_SORT_MODAL: 'CLOSE_SORT_MODAL',

  OPEN_MOVEFILES_MODAL: 'OPEN_MOVEFILES_MODAL',
  CLOSE_MOVEFILES_MODAL: 'CLOSE_MOVEFILES_MODAL',

  OPEN_CREATE_FOLDER_FORM: 'OPEN_CREATE_FOLDER_FORM',
  CLOSE_CREATE_FOLDER_FORM: 'CLOSE_CREATE_FOLDER_FORM',
  
  OPEN_FREEFORYOU_MODAL: 'OPEN_FREEFORYOU_MODAL',
  CLOSE_FREEFORYOU_MODAL: 'CLOSE_FREEFORYOU_MODAL',

  OPEN_DELETE_MODAL: 'OPEN_DELETE_MODAL',
  CLOSE_DELETE_MODAL: 'CLOSE_DELETE_MODAL',

  OPEN_SHARE_MODAL: 'OPEN_SHARE_MODAL',
  CLOSE_SHARE_MODAL: 'CLOSE_SHARE_MODAL'
};
