export const layoutActionTypes = {
  OPEN_SEARCH_FORM: '[Layout] Open Search Form',
  CLOSE_SEARCH_FORM: '[Layout] Close Search Form',
  OPEN_SETTINGS_MODAL: 'OPEN_SETTINGS_MODAL',
  CLOSE_SETTINGS_MODAL: 'CLOSE_SETTINGS_MODAL',
  OPEN_ITEM_MODAL: 'OPEN_ITEM_MODAL',
  CLOSE_ITEM_MODAL: 'CLOSE_ITEM_MODAL',
  OPEN_RUNOUTSTORAGE_MODAL: 'OPEN_RUNOUTSTORAGE_MODAL',
  CLOSE_RUNOUTSTORAGE_MODAL: 'CLOSE_RUNOUTSTORAGE_MODAL',
  OPEN_SORT_MODAL: 'OPEN_SORT_MODAL',
  CLOSE_SORT_MODAL: 'CLOSE_SORT_MODAL',
  OPEN_MOVEFILES_MODAL: 'OPEN_MOVEFILES_MODAL',
  CLOSE_MOVEFILES_MODAL: 'CLOSE_MOVEFILES_MODAL',
  OPEN_CREATE_FOLDER_FORM: 'OPEN_CREATE_FOLDER_FORM',
  CLOSE_CREATE_FOLDER_FORM: 'CLOSE_CREATE_FOLDER_FORM',
  OPEN_FREEFORYOU_MODAL: 'OPEN_FREEFORYOU_MODAL',
  CLOSE_FREEFORYOU_MODAL: 'CLOSE_FREEFORYOU_MODAL'
};
