export const photoActionTypes = {
  START_SYNC: 'START_SYNC',
  STOP_SYNC: 'STOP_SYNC',
  START_SAVE_DB: 'START_SAVE_DB',
  VIEW_DB: 'VIEW_DB',
  ADD_PHOTOS_TO_RENDER: 'ADD_PHOTOS_TO_RENDER',
  PHOTO_UPLOAD_UPDATE: 'PHOTO_UPLOAD_UPDATE',
  PHOTO_DOWNLOAD_UPDATE: 'PHOTO_DOWNLOAD_UPDATE',
  PHOTO_SELECTION_UPDATE: 'PHOTO_SELECTION_UPDATE',
  PHOTO_SELECTION_CLEAR: 'PHOTO_SELECTION_CLEAR',
  PHOTO_STATUS_UPDATE: 'PHOTO_STATUS_UPDATE',
  CLEAR_PHOTOS_TO_RENDER: 'CLEAR_PHOTOS_TO_RENDER'
}