export const photoActionTypes = {
  SET_PHOTOS_TO_RENDER: 'SET_PHOTOS_TO_RENDER',
  PUSH_DOWNLOADED_PHOTO: 'PUSH_DOWNLOADED_PHOTO',
  START_PHOTO_UPLOAD: 'START_PHOTO_UPLOAD',
  STOP_PHOTO_UPLOAD: 'STOP_PHOTO_UPLOAD',
  START_PHOTO_DOWNLOAD: 'START_PHOTO_DOWNLOAD',
  STOP_PHOTO_DOWNLOAD: 'STOP_PHOTO_DOWNLOAD',
  START_SYNC: 'START_SYNC',
  STOP_SYNC: 'STOP_SYNC',
  START_SAVE_DB: 'START_SAVE_DB',
  VIEW_DB: 'VIEW_DB'
}