export const userActionTypes = {
  SIGNIN_REQUEST: 'USER_SIGNIN_REQUEST',
  SIGNIN_SUCCESS: 'USER_SIGNIN_SUCCESS',
  SIGNIN_FAILURE: 'USER_SIGNIN_FAILURE',

  SIGNOUT: 'USER_SIGNOUT',

  LOCAL_SIGNIN: 'USER_LOCAL_SIGNIN',

  PAYMENT_REQUEST: 'PAYMENT_REQUEST',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILURE: 'PAYMENT_FAILURE'
};
