name: Mobile - Lint and Unit Tests
on:
  push:
    branches: ['**']
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: echo "registry=https://registry.yarnpkg.com/" > .npmrc
      - run: echo "@internxt:registry=https://npm.pkg.github.com" >> .npmrc
      - run: echo //npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }} >> .npmrc
      - run: echo "always-auth=true" >> .npmrc

      - name: Install
        run: yarn --prefer-offline

      - name: Prepare env files
        run: yarn run prepare-env

      - name: Lint
        run: yarn run lint

      - name: Test
        run: yarn run test:unit
