name: Mobile - Unit Tests
on:
  push:
    branches: ['**']
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install
        run: yarn --prefer-offline

      - name: Prepare env files
        run: yarn run prepare-env

      - name: Test
        run: yarn run test:unit
